// * * * COMPONENTE EDITOR DE CODIGO LADO A LADO Y EXPORTADOR ZIP * * *
import React, { useState, useEffect } from 'react';
import { Code2, Copy, Check, FolderTree, FileCode, Upload, Archive } from 'lucide-react';
import JSZip from 'jszip';
import { TRANSLATIONS } from '../data/translations';

export default function CodeEditor({ project, transpiledCode, isTranspiling, isVerified, providerName, onUploadCode, lang = 'es' }) {
  // * * * CARGA DE TRADUCCIONES SEGUN EL IDIOMA * * *
  const t = TRANSLATIONS[lang] || TRANSLATIONS.es;

  // * * * ESTADOS INTERNOS DE COPIADO Y PESTAÑAS DEL EDITOR * * *
  const [copiedLegacy, setCopiedLegacy] = useState(false);
  const [copiedTarget, setCopiedTarget] = useState(false);
  const [activeTab, setActiveTab] = useState('editor');
  
  const fileTree = project.fileTree || [{ name: 'Main.java', path: 'Main.java', selected: true }];
  const [selectedFile, setSelectedFile] = useState(fileTree[0]);
  const [isZipping, setIsZipping] = useState(false);

  // * * * SINCRONIZACION DEL ARCHIVO SELECCIONADO AL CAMBIAR PROYECTO * * *
  useEffect(() => {
    if (project.fileTree && project.fileTree.length > 0) {
      setSelectedFile(project.fileTree[0]);
    }
  }, [project]);

  // * * * OBTENCION DINAMICA DEL CODIGO FUENTE ACTIVO * * *
  const getActiveSourceCode = () => {
    if (!selectedFile) return project.sourceCode;
    if (selectedFile.source) return selectedFile.source;
    if (selectedFile.content) return selectedFile.content;
    return project.sourceCode;
  };

  // * * * OBTENCION DINAMICA DEL CODIGO TRANSPILADO ACTIVO * * *
  const getActiveTargetCode = () => {
    if (transpiledCode && selectedFile?.name === fileTree[0]?.name) return transpiledCode;
    if (selectedFile && selectedFile.target) return selectedFile.target;
    return project.targetCode;
  };

  // * * * MANEJADOR DE COPIADO AL PORTAPAPELES * * *
  const handleCopy = (text, type) => {
    navigator.clipboard.writeText(text);
    if (type === 'legacy') {
      setCopiedLegacy(true);
      setTimeout(() => setCopiedLegacy(false), 2000);
    } else {
      setCopiedTarget(true);
      setTimeout(() => setCopiedTarget(false), 2000);
    }
  };

  // * * * GENERACION Y DESCARGA DEL ARCHIVO BUNDLE ZIP EN EL CLIENTE * * *
  const handleDownloadTranspiledZip = async () => {
    setIsZipping(true);
    const zip = new JSZip();
    const isRust = project.targetLanguage.includes('Rust');
    
    const cleanName = project.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    const folderName = `transpiled-${cleanName}`;
    const projectFolder = zip.folder(folderName);

    // * * * EMPAQUETADO DE ARCHIVOS EN LA ESTRUCTURA RUST * * *
    fileTree.forEach((file) => {
      const ext = isRust ? (file.name.endsWith('.xml') ? 'toml' : 'rs') : (file.name.endsWith('.xml') ? 'json' : 'ts');
      const transpiledFileName = file.name.endsWith('.xml') ? 'Cargo.toml' : file.name.replace(/\.(java|py|cs|js)$/, `.${ext}`);
      
      const fileCode = (transpiledCode && file.name === fileTree[0]?.name)
        ? transpiledCode
        : (file.target || project.targetCode);
      
      if (file.name.endsWith('.xml')) {
        projectFolder.file(transpiledFileName, fileCode);
      } else {
        projectFolder.file(`src/${transpiledFileName}`, fileCode);
      }
    });

    if (isRust && !fileTree.some(f => f.name.endsWith('.xml'))) {
      projectFolder.file("Cargo.toml", `[package]\nname = "aws-lambda-rust-order-service"\nversion = "1.0.0"\nedition = "2021"\n\n[dependencies]\nlambda_runtime = "0.8"\nlambda_http = "0.8"\ntokio = { version = "1.28", features = ["full"] }\nserde = { version = "1.0", features = ["derive"] }\nserde_json = "1.0"\naws-config = "0.55"\naws-sdk-dynamodb = "0.28"\nuuid = { version = "1.3", features = ["v4", "fast-rng"] }\nanyhow = "1.0"`);
    }

    projectFolder.file("README_AWS.md", `# AWS Serverless Transpiled Output\nGenerated by Kiro-PolyGlot Engine for ${project.name}.\n\n## Deployment\nDeploy using AWS SAM:\n\`\`\`bash\nsam build\nsam deploy --guided\n\`\`\``);

    const content = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(content);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${folderName}.zip`;
    link.click();
    URL.revokeObjectURL(url);
    setIsZipping(false);
  };

  // * * * SOPORTE PARA SCROLL HORIZONTAL CON LA RUEDA DEL MOUSE * * *
  const handleHorizontalWheel = (e) => {
    if (e.deltaY) {
      e.currentTarget.scrollLeft += e.deltaY;
    }
  };

  // * * * RENDERIZADO HIGHLIGHTED DE LINEAS DE CODIGO Y OPTIMIZACIONES * * *
  const renderCodeLines = (code, isLegacy = false) => {
    const lines = (code || '').trim().split('\n');
    return lines.map((line, i) => {
      const isBottleneck = isLegacy && (line.includes('BOTTLE-NECK') || line.includes('sleep') || line.includes('JDBC') || line.includes('Reflection'));
      const isOptimization = !isLegacy && (line.includes('OPTIMIZATION') || line.includes('DynamoDB') || line.includes('docClient') || line.includes('handler'));

      return (
        <div
          key={i}
          className={`flex items-start px-4 py-0.5 font-mono text-xs leading-relaxed hover:bg-[#313244]/40 ${
            isBottleneck ? 'bg-[#f38ba8]/10 text-[#f38ba8]' : ''
          } ${isOptimization ? 'bg-[#a6e3a1]/10 text-[#a6e3a1]' : ''}`}
        >
          <span className="w-8 shrink-0 text-[#6c7086] select-none text-right pr-3 font-mono text-[11px]">
            {i + 1}
          </span>
          <span className="whitespace-pre flex-1 text-[#cdd6f4]">
            {line}
          </span>
        </div>
      );
    });
  };

  return (
    <div className="space-y-3 animate-fade-in">
      
      {/* * * * BARRA DE HERRAMIENTAS SUB-HEADER * * * */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-3 bg-[#1e1e2e] border border-[#313244] rounded-xl p-2.5">
        <div className="flex items-center gap-1.5">
          <button
            onClick={() => setActiveTab('editor')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
              activeTab === 'editor'
                ? 'bg-[#313244] text-[#cdd6f4]'
                : 'text-[#a6adc8] hover:text-[#cdd6f4]'
            }`}
          >
            <Code2 className="w-3.5 h-3.5 text-[#cba6f7]" />
            <span>{t.sideBySide}</span>
          </button>
          
          <button
            onClick={() => setActiveTab('explorer')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
              activeTab === 'explorer'
                ? 'bg-[#313244] text-[#cdd6f4]'
                : 'text-[#a6adc8] hover:text-[#cdd6f4]'
            }`}
          >
            <FolderTree className="w-3.5 h-3.5 text-[#89b4fa]" />
            <span>{t.fileTree} ({fileTree.length})</span>
          </button>
        </div>

        <button
          onClick={onUploadCode}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-[#181825] border border-[#313244] text-xs text-[#a6adc8] hover:text-[#cdd6f4] transition-all font-medium"
        >
          <Upload className="w-3.5 h-3.5" />
          <span>{t.uploadFiles}</span>
        </button>
      </div>

      {/* * * * VISTA DEL ARBOL DE ARCHIVOS * * * */}
      {activeTab === 'explorer' && (
        <div className="bg-[#1e1e2e] border border-[#313244] rounded-xl p-4 animate-fade-in">
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-2">
            {fileTree.map((file, idx) => {
              const isSelected = selectedFile?.name === file.name;
              return (
                <button
                  key={idx}
                  onClick={() => setSelectedFile(file)}
                  className={`p-2.5 rounded-lg border text-left font-mono text-xs transition-all flex items-center justify-between ${
                    isSelected
                      ? 'bg-[#cba6f7]/15 border-[#cba6f7] text-[#cba6f7] font-semibold'
                      : 'bg-[#181825] border-[#313244] text-[#a6adc8] hover:text-[#cdd6f4]'
                  }`}
                >
                  <span className="truncate">{file.name}</span>
                  <FileCode className="w-3.5 h-3.5 shrink-0" />
                </button>
              );
            })}
          </div>
        </div>
      )}

      {/* * * * EDITORES DE CODIGO LADO A LADO * * * */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
        
        {/* * * * PANEL IZQUIERDO: CODIGO FUENTE (ORIGEN) * * * */}
        <div className="bg-[#1e1e2e] rounded-xl border border-[#313244] overflow-hidden flex flex-col h-[520px]">
          <div className="bg-[#181825] px-3.5 py-2 border-b border-[#313244] flex items-center justify-between gap-2">
            <div className="flex items-center gap-2 min-w-0">
              <span className="text-xs font-semibold text-[#f38ba8] font-mono truncate">
                {t.originLegacy}: {selectedFile ? selectedFile.name : 'Legacy'}
              </span>
              <span className="px-2 py-0.5 text-[10px] bg-[#313244] text-[#a6adc8] rounded font-mono font-medium shrink-0">
                {project.sourceLanguage}
              </span>
            </div>

            <button
              onClick={() => handleCopy(getActiveSourceCode(), 'legacy')}
              className="flex items-center gap-1 px-2.5 py-1 rounded bg-[#313244] text-xs text-[#a6adc8] hover:text-[#cdd6f4] font-mono transition-colors shrink-0"
            >
              {copiedLegacy ? <Check className="w-3.5 h-3.5 text-[#a6e3a1]" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedLegacy ? t.copied : t.copy}</span>
            </button>
          </div>

          <div
            onWheel={handleHorizontalWheel}
            className="bg-[#181825] px-2 py-1.5 border-b border-[#313244] flex items-center gap-1.5 overflow-x-auto select-none"
          >
            {fileTree.map((file, idx) => (
              <button
                key={idx}
                onClick={() => setSelectedFile(file)}
                className={`flex items-center gap-1.5 px-3 py-1 rounded-md text-xs font-mono transition-all shrink-0 border ${
                  selectedFile?.name === file.name
                    ? 'bg-[#cba6f7] text-[#11111b] border-[#cba6f7] font-semibold'
                    : 'bg-[#1e1e2e] border-[#313244] text-[#a6adc8] hover:text-[#cdd6f4]'
                }`}
              >
                <FileCode className="w-3.5 h-3.5 text-[#89b4fa]" />
                <span>{file.name}</span>
              </button>
            ))}
          </div>

          <div className="overflow-y-auto py-2 bg-[#11111b] flex-1">
            {renderCodeLines(getActiveSourceCode(), true)}
          </div>
        </div>

        {/* * * * PANEL DERECHO: CODIGO TRANSPILADO (DESTINO AWS SERVERLESS) * * * */}
        <div className="bg-[#1e1e2e] rounded-xl border border-[#313244] overflow-hidden flex flex-col h-[520px]">
          <div className="bg-[#181825] px-3.5 py-2 border-b border-[#313244] flex items-center justify-between gap-2">
            <div className="flex items-center gap-2 min-w-0">
              <span className="text-xs font-semibold text-[#a6e3a1] font-mono truncate">
                {t.transpiledTarget}: {selectedFile ? selectedFile.name : 'Target'}
              </span>
              <span className="px-2 py-0.5 text-[10px] bg-[#313244] text-[#a6adc8] rounded font-mono font-medium shrink-0">
                {project.targetLanguage}
              </span>
            </div>

            <div className="flex items-center gap-1.5 shrink-0">
              <button
                onClick={handleDownloadTranspiledZip}
                disabled={isZipping}
                className="flex items-center gap-1 px-2.5 py-1 rounded bg-[#a6e3a1] text-[#11111b] text-xs font-bold font-mono hover:opacity-90 transition-all shrink-0"
              >
                <Archive className="w-3.5 h-3.5" />
                <span>{t.downloadZip}</span>
              </button>

              <button
                onClick={() => handleCopy(getActiveTargetCode(), 'target')}
                className="flex items-center gap-1 px-2.5 py-1 rounded bg-[#313244] text-xs text-[#a6adc8] hover:text-[#cdd6f4] font-mono transition-colors shrink-0"
              >
                {copiedTarget ? <Check className="w-3.5 h-3.5 text-[#a6e3a1]" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedTarget ? t.copied : t.copy}</span>
              </button>
            </div>
          </div>

          <div className="overflow-y-auto py-2 bg-[#11111b] flex-1">
            {renderCodeLines(getActiveTargetCode(), false)}
          </div>
        </div>

      </div>
    </div>
  );
}
